<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gsn" nsURI="http://papyrus/gsn" nsPrefix="GSN">
  <eClassifiers xsi:type="ecore:EClass" name="CoreElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Identifier" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Statement" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Undeveloped" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Uninstantiated" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eSubpackages name="Core" nsURI="http:///gsn/Core.ecore" nsPrefix="gsn.Core">
    <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//CoreElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Strategy" eSuperTypes="#//CoreElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Solution" eSuperTypes="#//CoreElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Context" eSuperTypes="#//CoreElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Justification" eSuperTypes="#//CoreElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Assumption" eSuperTypes="#//CoreElement"/>
  </eSubpackages>
  <eSubpackages name="Associations" nsURI="http:///gsn/Associations.ecore" nsPrefix="gsn.Associations">
    <eClassifiers xsi:type="ecore:EClass" name="SupportedBy">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Association" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NarySupportedBy">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="N-arySupportedBy"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Association" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OptionnalSupportedBy">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Association" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OptionnalInContextOf">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Association" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NaryInContextOf">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="N-aryInContextOf"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Association" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InContextOf">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Association" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="ModularExtensions" nsURI="http:///gsn/ModularExtensions.ecore"
      nsPrefix="gsn.ModularExtensions">
    <eClassifiers xsi:type="ecore:EClass" name="AwayGoal" eSuperTypes="#//CoreElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ModuleIdentifierReference"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AwaySolution" eSuperTypes="#//CoreElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ModuleIdentifierReference"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AwayContext" eSuperTypes="#//CoreElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ModuleIdentifierReference"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModuleReference" eSuperTypes="#//CoreElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ContractModuleReference" eSuperTypes="#//CoreElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Module">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ModuleIdentifier" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContractModule" eSuperTypes="#//ModularExtensions/Module"/>
  </eSubpackages>
</ecore:EPackage>
