<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pattern" nsURI="http:///pattern.ecore" nsPrefix="pattern">
  <eSubpackages name="HighLevelVehicleSafetyArgument" nsURI="http:///pattern/HighLevelVehicleSafetyArgument.ecore"
      nsPrefix="pattern.HighLevelVehicleSafetyArgument">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="High Level Vehicle Safety Argument"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Goal1"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class2"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class3"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class4"/>
    <eClassifiers xsi:type="ecore:EClass" name="Strategy5"/>
    <eClassifiers xsi:type="ecore:EClass" name="Strategy6"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class7"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class8"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class9"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class10"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class11"/>
  </eSubpackages>
  <eSubpackages name="InstantiationoftheRiskManagement" nsURI="http:///pattern/InstantiationoftheRiskManagement.ecore"
      nsPrefix="pattern.InstantiationoftheRiskManagement">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Instantiation of the Risk Management"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Goal1"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class2"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class3"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class4"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class5"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class6"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class7"/>
    <eClassifiers xsi:type="ecore:EClass" name="Goal8"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class9"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class10"/>
    <eClassifiers xsi:type="ecore:EClass" name="Strategy11"/>
    <eClassifiers xsi:type="ecore:EClass" name="Goal12"/>
    <eClassifiers xsi:type="ecore:EClass" name="Strategy13"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class14"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class15"/>
    <eClassifiers xsi:type="ecore:EClass" name="Goal16"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class17"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class18"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class19"/>
  </eSubpackages>
  <eSubpackages name="PredefinedSafetyRequirements" nsURI="http:///pattern/PredefinedSafetyRequirements.ecore"
      nsPrefix="pattern.PredefinedSafetyRequirements">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Predefined Safety Requirements"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Goal1"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class2"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class3"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class4"/>
    <eClassifiers xsi:type="ecore:EClass" name="Strategy5"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class6"/>
    <eClassifiers xsi:type="ecore:EClass" name="Goal7"/>
    <eClassifiers xsi:type="ecore:EClass" name="Goal8"/>
    <eClassifiers xsi:type="ecore:EClass" name="Goal9"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class10"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class11"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class12"/>
  </eSubpackages>
  <eSubpackages name="RiskReductionthroughFunctionalityRestriction" nsURI="http:///pattern/RiskReductionthroughFunctionalityRestriction.ecore"
      nsPrefix="pattern.RiskReductionthroughFunctionalityRestriction">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Risk Reduction through Functionality Restriction"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Class1"/>
    <eClassifiers xsi:type="ecore:EClass" name="Goal2"/>
    <eClassifiers xsi:type="ecore:EClass" name="Goal3"/>
    <eClassifiers xsi:type="ecore:EClass" name="Goal4"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class5"/>
  </eSubpackages>
</ecore:EPackage>
